INSERT INTO questions (text, dimension, direction, weight) VALUES

('Ik maak me veel zorgen', 'EI', -1, 1),
('Ik maak gemakkelijk vrienden', 'EI', 1, 1),
('Ik hou van grote feesten en bijeenkomsten', 'EI', 1, 1),
('Ik heb moeite om anderen te benaderen', 'EI', -1, 1),
('Ik kan me soms behoorlijk laten gaan', 'EI', -1, 1),
('Ik hou van opwinding en spanning', 'EI', 1, 1),
('Ik ben een heel vrolijk persoon', 'EI', 1, 1),
('Ik voel me op mijn gemak bij andere mensen', 'EI', 1, 1),
('Ik praat met veel verschillende mensen op feestjes', 'EI', 1, 1),
('Ik heb soms een hekel aan mezelf', 'EI', -1, 1),
('Ik ben bang om de aandacht op mezelf te vestigen', 'EI', -1, 1),
('Ik hou het liever bij het bekende', 'EI', -1, 1),
('Ik schreeuw tegen anderen', 'EI', -1, 1),
('Ik vind mezelf erg goed', 'EI', 1, 1),
('Ik raak overweldigd door gebeurtenissen', 'EI', -1, 1),
('Ik vermijd contact met anderen als dat mogelijk is', 'EI', -1, 1),
('Ik ben graag op mezelf', 'EI', -1, 1),
('Ik ben soms gedeprimeerd', 'EI', -1, 1),
('Ik voel me alleen echt op mijn gemak bij vrienden', 'EI', -1, 1),
('Ik doe veel in mijn vrije tijd', 'EI', 1, 1),
('Ik heb een hoge dunk van mezelf', 'EI', 1, 1),
('Ik hou van het leven', 'EI', 1, 1),
('Ik hou mensen op een afstand', 'EI', -1, 1),
('Ik vermijd grote menigten', 'EI', -1, 1),
('Ik heb een goed gevoel over mezelf', 'EI', 1, 1),
('Ik laat anderen graag de leiding nemen', 'EI', -1, 1),
('Ik ervaar geen last in moeilijke sociale situaties', 'EI', 1, 1),
('Ik reageer traag', 'EI', -1, 1),
('Ik praat graag over mijn sterke punten', 'EI', 1, 1),
('Ik heb een positieve instelling', 'EI', 1, 1),

('Ik heb vertrouwen in anderen', 'TF', 1, 1),
('Ik word snel boos', 'TF', -1, 1),
('Ik misleid soms anderen om mijn zin te krijgen', 'TF', -1, 1),
('Ik voel me vaak verdrietig', 'TF', -1, 1),
('Ik ervaar sterke en gevarieerde emoties', 'TF', 1, 1),
('Ik help anderen graag', 'TF', 1, 1),
('Ik vind mezelf beter dan anderen', 'TF', -1, 1),
('Ik ben snel in paniek', 'TF', -1, 1),
('Ik heb medelijden met daklozen', 'TF', 1, 1),
('Ik vrees vaak het ergste', 'TF', -1, 1),
('Ik denk dat mensen in principe goede bedoelingen hebben', 'TF', 1, 1),
('Ik raak snel geïrriteerd', 'TF', -1, 1),
('Ik vind het niet erg om te bedriegen om hogerop te komen', 'TF', -1, 1),
('Ik voel de emoties van anderen aan', 'TF', 1, 1),
('Ik bekommer me om andere mensen', 'TF', 1, 1),
('Ik spreek de waarheid', 'TF', 1, 1),
('Ik kan me uitstekend matigen en inhouden', 'TF', 1, 1),
('Ik heb veel plezier', 'TF', 1, 1),
('Ik heb te doen met personen die het slechter hebben dan ik', 'TF', 1, 1),
('Ik maak overhaaste beslissingen', 'TF', -1, 1),
('Ik verlies vaak mijn kalmte', 'TF', -1, 1),
('Ik maak soms gebruik van anderen', 'TF', -1, 1),
('Ik merk mijn gevoelens en emoties vaak niet op', 'TF', -1, 1),
('Ik interesseer me niet voor andermans gevoelens', 'TF', -1, 1),
('Ik beledig mensen', 'TF', -1, 1),
('Ik heb geen interesse in andermans problemen', 'TF', -1, 1),
('Ik raak snel gestrest', 'TF', -1, 1),
('Ik wantrouw mensen', 'TF', -1, 1),
('Ik erger me niet gauw', 'TF', 1, 1),
('Ik werk soms niet mee en belemmer plannen van anderen', 'TF', -1, 1),
('Ik begrijp mensen die emotioneel worden niet', 'TF', -1, 1),
('Ik neem geen tijd voor anderen', 'TF', -1, 1),
('Ik houd mijn beloftes soms niet', 'TF', -1, 1),
('Ik neem wraak op anderen', 'TF', -1, 1),
('Ik vind dat we heel hard tegen criminaliteit moeten optreden', 'TF', 1, 1),
('Ik probeer niet veel na te denken over hulpbehoevenden', 'TF', -1, 1),
('Ik blijf kalm onder druk', 'TF', 1, 1),

('Ik heb een levendige fantasie', 'SN', 1, 1),
('Ik vind kunst belangrijk', 'SN', 1, 1),
('Ik hou van strijd en een stevige discussie', 'SN', -1, 1),
('Ik lees graag uitdagende boeken en artikelen', 'SN', 1, 1),
('Ik kies vaak voor verandering en progressief beleid', 'SN', 1, 1),
('Ik laat mijn verbeelding graag de vrije loop', 'SN', 1, 1),
('Ik zie de schoonheid van dingen die anderen niet opvallen', 'SN', 1, 1),
('Ik ben erg op zoek naar avontuur', 'SN', 1, 1),
('Ik vermijd filosofische discussies', 'SN', -1, 1),
('Ik geloof niet in absoluut goed of absoluut fout', 'SN', 1, 1),
('Ik ben voor veel dingen bang', 'SN', -1, 1),
('Ik hou van dagdromen', 'SN', 1, 1),
('Ik hou niet van poëzie', 'SN', -1, 1),
('Ik vertrouw wat anderen zeggen', 'SN', -1, 1),
('Ik heb moeite met het begrijpen van abstracte ideeën', 'SN', -1, 1),
('Ik raak graag in mijn gedachten verzonken', 'SN', 1, 1),
('Ik ga niet graag naar musea of tentoonstellingen', 'SN', -1, 1),
('Ik hecht veel belang aan tradities en gewoonten', 'SN', -1, 1),
('Ik ben niet geïnteresseerd in theoretische discussies', 'SN', -1, 1),

('Ik breng taken tot een goed einde', 'JP', 1, 1),
('Ik hou niet van wanorde en ruim graag op', 'JP', 1, 1),
('Ik neem graag de leiding in situaties en bij gebeurtenissen', 'JP', 1, 1),
('Ik houd altijd mijn beloftes', 'JP', 1, 1),
('Ik ben altijd bezig en druk met dingen', 'JP', 1, 1),
('Ik verkies afwisseling boven routine', 'JP', -1, 1),
('Ik ben een zeer harde werker', 'JP', 1, 1),
('Ik ben altijd voorbereid', 'JP', 1, 1),
('Ik ben erg spontaan en reageer zonder na te denken', 'JP', -1, 1),
('Ik doe de dingen die ik doe altijd goed', 'JP', 1, 1),
('Ik vergeet vaak dingen op de juiste plaats terug te leggen', 'JP', -1, 1),
('Ik probeer anderen te sturen en dingen te bepalen', 'JP', 1, 1),
('Ik zit nooit stil en ben altijd in de weer', 'JP', 1, 1),
('Ik doe meer dan wat van mij wordt verwacht', 'JP', 1, 1),
('Ik voer mijn plannen en taken uit', 'JP', 1, 1),
('Ik laat zaken soms rommelig achter', 'JP', -1, 1),
('Ik neem de controle in handen', 'JP', 1, 1),
('Ik hou me niet aan de regels', 'JP', -1, 1),
('Ik hou niet van veranderingen', 'JP', -1, 1),
('Ik doe niet meer dan strikt nodig is', 'JP', -1, 1),
('Ik kan verleidingen gemakkelijk weerstaan', 'JP', 1, 1),
('Ik hou van risico', 'JP', -1, 1),
('Ik verknoei mijn tijd', 'JP', -1, 1),
('Ik heb het gevoel dingen niet aan te kunnen', 'JP', -1, 1),
('Ik vind dat de wet strikt moet worden nageleefd', 'JP', 1, 1),
('Ik begin overhaast aan dingen', 'JP', -1, 1),
('Ik weet hoe zaken moeten worden aangepakt', 'JP', 1, 1),
('Ik laat dingen en bezittingen rondslingeren', 'JP', -1, 1),
('Ik investeer soms weinig tijd en moeite in mijn werkzaamheden', 'JP', -1, 1),
('Ik kan sterke behoeftes onder controle houden', 'JP', 1, 1),
('Ik hou van actie en gevaar', 'JP', -1, 1),
('Ik heb moeite om met iets te beginnen', 'JP', -1, 1),
('Ik voer taken methodisch uit', 'JP', 1, 1),
('Ik handel zonder er over na te denken', 'JP', -1, 1);
